title:        Todd Grooms
tagline:      'The homepage for Todd Grooms'
description:  'This is the homepage of <a href="http://toddgrooms.com">Todd Grooms</a>.'
url:          http://groomsydev.org
version:      0.0.2
author:
  name:       'Todd Grooms'
  email:      'todd.grooms@gmail.com'
markdown:     rdiscount
permalink:    pretty
highlighter:     true
paginate:     5
