# Site settings
title:              Todd Grooms Weblog
email:              todd.grooms@gmail.com
author:             Todd Grooms
description:        'Cage free, organic, all natural weblog.'
baseurl:
url:                'http://toddgrooms.com'

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons:  false
github_username:    groomsy
twitter_username:   toddgrooms
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
permalink:          pretty
paginate:           5
sass:
  compressed:       true
timezone:           'America/Memphis'

# Exclude tools
exclude:            [blog-tools, Gemfile, Gemfile.lock, License.md, README.md, scenic, appcasts, advanced-layouts-with-auto-layout]
