# Site settings
title:              Todd Grooms.com
email:              todd.grooms@gmail.com
author:             Todd Grooms
description:        'Todd Grooms'
baseurl:
url:                'http://groomsy.github.io'

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  true

# Social icons
show_social_icons:  true
github_username:    groomsy
twitter_username:   toddgrooms
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
permalink:          pretty
paginate:           5
sass:
  compressed:       true
timezone:           'America/Chicago'
