# Site settings
title:        Todd Grooms Weblog
email:        toddgrooms@fastmail.fm
description:  >- # this means to ignore newlines until "baseurl:"
  The weblog of Todd Grooms. Chronocling one software developer's journey
  through this thing we call life.
baseurl:      "" # the subpath of your site, e.g. /blog
url:          "https://www.toddgrooms.com"

show_social_icons:  false
twitter_username:   toddgrooms
github_username:    groomsy

# Build settings
markdown:   kramdown
permalink:  pretty
pagination:
  enabled:      true
  debug:        true
  limit:        0
  per_page:     10
  permalink:    '/page/:num/'
  sort_field:   'date'
  sort_reverse: true
plugins:
  - jekyll-paginate-v2     # pagination
  - jekyll_version_plugin  # displaying build number on site
timezone:   'America/Memphis'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - License.md
  - README.md
  - advanced-layouts-with-auto-layout
  - appcasts
  - blog-tools
  - scenic
