title:        GroomsyDev
tagline:      'The development homepage for Todd Grooms'
description:  'This homepage is for the development related musings of <a href="http://toddgrooms.com">Todd Grooms</a>.'
url:          http://groomsydev.org
version:      0.0.1
author:
  name:       'Todd Grooms'
  email:      'todd.grooms@gmail.com'
markdown:     rdiscount
permalink:    pretty
highlighter:     true
paginate:     5
