name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Setup Environment
        run: |
          gem install jekyll bundler
          bundle install

      - name: Build Site with Jekyll
        run: |
          JEKYLL_ENV=production bundle exec jekyll build

      - run: echo "🍏 This job's status is ${{ job.status }}."